# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'passcipher\ui\add_account.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(426, 415)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 406, 395))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.account_heading = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.account_heading.setObjectName("account_heading")
        self.verticalLayout.addWidget(self.account_heading)
        self.account_input = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.account_input.setMaximumSize(QtCore.QSize(16777215, 30))
        self.account_input.setObjectName("account_input")
        self.verticalLayout.addWidget(self.account_input)
        self.username_heading = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.username_heading.setObjectName("username_heading")
        self.verticalLayout.addWidget(self.username_heading)
        self.username_input = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.username_input.setMaximumSize(QtCore.QSize(16777215, 30))
        self.username_input.setObjectName("username_input")
        self.verticalLayout.addWidget(self.username_input)
        self.url_heading = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.url_heading.setObjectName("url_heading")
        self.verticalLayout.addWidget(self.url_heading)
        self.url_input = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.url_input.setMaximumSize(QtCore.QSize(16777215, 30))
        self.url_input.setObjectName("url_input")
        self.verticalLayout.addWidget(self.url_input)
        self.cipher_heading = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.cipher_heading.setObjectName("cipher_heading")
        self.verticalLayout.addWidget(self.cipher_heading)
        self.cipher_choice = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.cipher_choice.setMinimumSize(QtCore.QSize(0, 30))
        self.cipher_choice.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cipher_choice.setObjectName("cipher_choice")
        self.cipher_choice.addItem("")
        self.cipher_choice.addItem("")
        self.verticalLayout.addWidget(self.cipher_choice)
        self.notes_heading = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.notes_heading.setObjectName("notes_heading")
        self.verticalLayout.addWidget(self.notes_heading)
        self.notes_input = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.notes_input.setMaximumSize(QtCore.QSize(16777215, 30))
        self.notes_input.setObjectName("notes_input")
        self.verticalLayout.addWidget(self.notes_input)
        self.group_heading = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.group_heading.setObjectName("group_heading")
        self.verticalLayout.addWidget(self.group_heading)
        self.group_input = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.group_input.setMaximumSize(QtCore.QSize(16777215, 30))
        self.group_input.setObjectName("group_input")
        self.verticalLayout.addWidget(self.group_input)
        self.create_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.create_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.create_btn.setMaximumSize(QtCore.QSize(16777215, 30))
        self.create_btn.setObjectName("create_btn")
        self.verticalLayout.addWidget(self.create_btn)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.account_heading.setText(_translate("Dialog", "Account Name"))
        self.username_heading.setText(_translate("Dialog", "Username"))
        self.url_heading.setText(_translate("Dialog", "URL"))
        self.cipher_heading.setText(_translate("Dialog", "Password Encyption Cipher"))
        self.cipher_choice.setItemText(0, _translate("Dialog", "Substitution Cipher"))
        self.cipher_choice.setItemText(1, _translate("Dialog", "Caesar Cipher"))
        self.notes_heading.setText(_translate("Dialog", "Notes"))
        self.group_heading.setText(_translate("Dialog", "Group"))
        self.create_btn.setText(_translate("Dialog", "Create"))
